name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow daily at midnight UTC
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}


      - name: Fetch content from Scrapeway
        id: fetch_content
        env:
          SCRAPEWAY_USERNAME: ${{ secrets.SCRAPEWAY_USERNAME }}
          SCRAPEWAY_PASSWORD: ${{ secrets.SCRAPEWAY_PASSWORD }}
        run: |
          content=$(curl -s https://scrapeway.com/?format=markdown)
          echo "$content" > README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md with content from Scrapeway"
          branch: main
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
